"""
Category-based rubric data extracted from Chapter 12.

Generated by scripts/extract_indicators.py from:
- Ch. 12 pattern descriptions (roadmap synthesis)
- Source chapter text (detailed pattern definitions)
- Claude-extracted binary indicators

Do not edit manually — re-run the extraction script to update.
"""


# ---------------------------------------------------------------------------
# Rubric: category -> levels -> patterns with indicators
# ---------------------------------------------------------------------------

RUBRIC: dict[str, dict] = {
    "coordination": {
        "name": "Coordination & Planning",
        "chapter": 5,
        "levels": {
            "basic": [
                {
                    "id": "supervisor_architecture",
                    "name": "Supervisor Architecture",
                    "indicators": [
                        "A single central orchestrator agent manages and delegates tasks to multiple specialized worker agents",
                        "The orchestrator receives results from worker agents and uses them to decide the next step in the workflow",
                        "Worker agents return structured data to the orchestrator rather than communicating directly with each other",
                        "The orchestrator maintains state and controls the sequential or conditional flow of task execution",
                    ],
                },
                {
                    "id": "multi_agent_planning",
                    "name": "Multi-Agent Planning",
                    "indicators": [
                        "A central orchestrator or supervisor agent breaks down user requests into a sequence of sub-tasks",
                        "Task decomposition logic uses either hardcoded workflows or simple dynamic sequencing based on predefined rules",
                        "The planning component assigns tasks to specialized worker agents rather than executing domain logic itself",
                        "Task execution follows a sequential or conditional flow where each step's completion triggers the next planned action",
                    ],
                },
            ],
            "intermediate": [
                {
                    "id": "hybrid_delegation_framework",
                    "name": "Hybrid Delegation Framework",
                    "indicators": [
                        "A top-level orchestrator agent delegates tasks to specialized worker agents or agent groups",
                        "Agent groups or swarms can self-organize and select tasks without central coordination",
                        "The system switches between centralized orchestration and decentralized swarm modes based on task characteristics",
                        "Task assignment logic includes both hierarchical delegation and peer-to-peer task bidding mechanisms",
                    ],
                },
                {
                    "id": "shared_epistemic_memory",
                    "name": "Shared Epistemic Memory",
                    "indicators": [
                        "A persistent storage system (database, Redis cache, or similar) is configured for shared agent memory access",
                        "Concurrency control mechanisms (locks, semaphores, or atomic operations) are implemented for memory access operations",
                        "Time-to-Live (TTL) policies or data expiration logic are configured for stored memory entries",
                        "Multiple agent classes or instances reference the same shared memory storage connection or interface",
                        "Semantic indexing or search capabilities (vector embeddings, search queries, or tagging) are implemented for memory retrieval",
                    ],
                },
            ],
            "advanced": [
                {
                    "id": "consensus_and_negotiation",
                    "name": "Consensus, Negotiation & Conflict Resolution",
                    "indicators": [
                        "Agents implement explicit consensus mechanisms that require agreement from multiple agents before proceeding",
                        "The system includes negotiation protocols where agents can exchange offers and counteroffers",
                        "Conflict resolution functions are invoked when agents have disagreeing outputs or conflicting resource requests",
                        "Agent interactions include debate or discussion phases where conflicting data is iteratively resolved",
                        "The architecture implements autonomous agent-to-agent communication without requiring supervisor approval for conflict resolution",
                    ],
                },
            ],
        },
    },
    "explainability": {
        "name": "Explainability & Compliance",
        "chapter": 6,
        "levels": {
            "basic": [
                {
                    "id": "basic_audit_logging",
                    "name": "Basic Audit Logging",
                    "indicators": [
                        "Agent actions are logged with timestamps, agent IDs, and outcome status to a file or console output",
                        "Log entries are generated before and after critical agent operations or decisions",
                        "A centralized logging mechanism captures audit trails across multiple agents in the system",
                        "Log messages include structured data fields for agent identification and action results",
                    ],
                },
            ],
            "intermediate": [
                {
                    "id": "instruction_fidelity_auditing",
                    "name": "Instruction Fidelity Auditing",
                    "indicators": [
                        "A specialized auditor agent verifies worker agent outputs against original instructions before finalizing actions",
                        "Worker agent outputs and original instructions are both passed as parameters to an audit verification function",
                        "The system includes logic to revert or reject actions when audit verification fails",
                        "Audit results contain explicit pass/fail status and reason fields that are checked before proceeding",
                        "Critical actions are blocked until receiving a successful audit verdict from the verification layer",
                    ],
                },
                {
                    "id": "persistent_instruction_anchoring",
                    "name": "Persistent Instruction Anchoring",
                    "indicators": [
                        "Critical instructions or constraints are wrapped in special tags or markers (e.g., PERSISTENT_GOAL, CRITICAL_INSTRUCTION, anchoring brackets)",
                        "The same anchored instruction string is passed through multiple agent calls in a workflow chain",
                        "Agent-to-agent communication includes the original anchored constraints alongside new task-specific data",
                        "A standardized format for instruction anchors is used consistently across different agent classes or functions",
                    ],
                },
                {
                    "id": "causal_dependency_graph",
                    "name": "Causal Dependency Graph",
                    "indicators": [
                        "Agent execution calls or decisions are logged with causal relationships or dependency links to other agents/decisions",
                        "The system maintains a structured graph or tree data structure that tracks decision lineage across multiple agents",
                        "Logging includes metadata that connects each agent's output to the specific inputs or prior decisions that influenced it",
                        "Decision audit trails can be traced backwards from any final outcome to identify all contributing agents and intermediate steps",
                    ],
                },
            ],
            "advanced": [
                {
                    "id": "fractal_cot_embedding",
                    "name": "Fractal CoT Embedding",
                    "indicators": [
                        "Agent reasoning processes include explicit self-correction loops that can revise previous reasoning steps",
                        "The system maintains a recursive thought structure where agents can refine their own conclusions based on new evidence",
                        "Agent prompts include template sections for objective function checks that evaluate thought validity against constraints",
                        "The architecture supports temporal re-grounding where earlier reasoning steps are formally updated rather than just appended to",
                        "Agents can dynamically adjust their context aperture to zoom in for detailed analysis or zoom out for broader perspective",
                    ],
                },
            ],
        },
    },
    "robustness": {
        "name": "Robustness & Fault Tolerance",
        "chapter": 7,
        "levels": {
            "basic": [
                {
                    "id": "watchdog_timeout",
                    "name": "Watchdog Timeout",
                    "indicators": [
                        "Agent function calls are wrapped with explicit timeout parameters or deadline mechanisms",
                        "Timeout violations trigger cancellation of the running agent task or operation",
                        "A fallback mechanism is invoked when timeout limits are exceeded",
                        "The system includes timer or timeout monitoring logic that runs concurrently with agent execution",
                    ],
                },
                {
                    "id": "simple_retry",
                    "name": "Simple Retry Mechanism",
                    "indicators": [
                        "Failed operations are retried with a fixed retry count before giving up",
                        "There is a loop or iteration construct that executes the same operation multiple times on failure",
                        "The retry mechanism includes a delay or wait period between retry attempts",
                    ],
                },
            ],
            "intermediate": [
                {
                    "id": "adaptive_retry_with_prompt_mutation",
                    "name": "Adaptive Retry with Prompt Mutation",
                    "indicators": [
                        "Retry logic modifies or mutates the original prompt/input when a previous attempt fails",
                        "The system implements a retry counter or attempt tracking mechanism that limits the number of retry attempts",
                        "Failed agent calls trigger prompt modification logic before the next retry attempt",
                        "The retry mechanism includes different prompt variations or prompt engineering strategies for subsequent attempts",
                    ],
                },
                {
                    "id": "auto_healing_agent_resuscitation",
                    "name": "Auto-Healing Agent Resuscitation",
                    "indicators": [
                        "Crashed or failed agent processes are automatically detected and restarted by infrastructure or a supervisor",
                        "Exponential backoff or maximum retry thresholds govern restart attempts to prevent infinite crash loops",
                        "Agent restart logic restores the agent's last known state from external storage rather than starting fresh",
                        "Health check or heartbeat mechanisms detect unresponsive agents and trigger resuscitation",
                    ],
                },
                {
                    "id": "incremental_checkpointing",
                    "name": "Incremental Checkpointing",
                    "indicators": [
                        "System periodically saves execution state or progress to persistent storage during long-running tasks",
                        "Recovery logic exists to restore agent state from previously saved checkpoints after interruption",
                        "Checkpoint data includes sufficient context to resume task execution from the saved point",
                        "Task execution can be resumed from an intermediate state rather than restarting from the beginning",
                    ],
                },
                {
                    "id": "fallback_model_invocation",
                    "name": "Fallback Model Invocation",
                    "indicators": [
                        "At least two LLM model configurations exist (primary and fallback) with the fallback used when the primary is unavailable",
                        "Primary model API calls have configured fallback models that are invoked when the primary fails or times out",
                        "The system contains conditional logic that switches to alternative models based on primary model availability or error responses",
                        "Fallback model invocation is triggered by specific error conditions such as API timeouts, rate limiting, or service unavailability",
                    ],
                },
                {
                    "id": "rate_limited_invocation",
                    "name": "Rate-Limited Invocation",
                    "indicators": [
                        "Outgoing API calls are throttled or queued to respect configured requests-per-second or tokens-per-minute limits",
                        "Rate limiting logic checks request counts against configured thresholds before allowing execution",
                        "Request rejection or throttling occurs when rate limits are exceeded",
                        "Rate limit counters or tracking mechanisms are implemented using time windows or token buckets",
                    ],
                },
            ],
            "advanced": [
                {
                    "id": "majority_voting",
                    "name": "Majority Voting Across Agents",
                    "indicators": [
                        "Multiple agents (3 or more) are invoked in parallel to perform the same task or decision",
                        "Agent outputs are compared using a numerical tolerance threshold or consensus logic",
                        "A conflict resolution mechanism exists for cases where agents disagree beyond the defined threshold",
                        "The system escalates to human review or a tie-breaker agent when majority consensus cannot be reached",
                    ],
                },
                {
                    "id": "trust_decay_and_scoring",
                    "name": "Trust Decay & Scoring",
                    "indicators": [
                        "Trust scores are numerically stored and tracked for individual agents over time",
                        "Task routing decisions reference agent trust/reputation scores to select between available agents",
                        "Trust scores are automatically decremented based on agent failure events or poor performance",
                        "An orchestrator component maintains and updates a reputation system or scoring mechanism for agents",
                    ],
                },
                {
                    "id": "canary_agent_testing",
                    "name": "Canary Agent Testing",
                    "indicators": [
                        "New agent versions are deployed alongside existing versions rather than replacing them immediately",
                        "Traffic routing logic exists to direct a percentage of requests to the canary version while the majority goes to the stable version",
                        "Output comparison logic exists to measure regression rate between canary and stable agent versions",
                        "Automatic rollback mechanisms are implemented to revert to the stable version when canary regression rate exceeds a threshold",
                    ],
                },
            ],
        },
    },
    "human_interaction": {
        "name": "Human-Agent Interaction",
        "chapter": 8,
        "levels": {
            "basic": [
                {
                    "id": "human_calls_agent",
                    "name": "Human Calls Agent",
                    "indicators": [
                        "User input is processed through a direct request-response cycle without multi-turn conversation state",
                        "The system uses intent classification or routing logic to map user queries to specific tools or functions",
                        "Tool or function calls are made synchronously with results returned directly to the user in the same interaction",
                        "Response generation formats tool outputs into human-readable messages before returning to user",
                    ],
                },
                {
                    "id": "agent_calls_human",
                    "name": "Agent Calls Human",
                    "indicators": [
                        "Agent workflow execution is paused or suspended when escalation conditions are met",
                        "Human escalation requests include structured context data packages with relevant state information",
                        "Agent confidence scores or thresholds are explicitly checked before triggering human escalation",
                        "A dedicated human review system or interface component handles escalation requests from agents",
                        "Agent resumes execution after receiving structured human decisions or responses",
                    ],
                },
            ],
            "intermediate": [
                {
                    "id": "agent_delegates_to_agent",
                    "name": "Agent Delegates to Agent",
                    "indicators": [
                        "A primary orchestrator agent delegates tasks to multiple specialist agents using function calls or message passing",
                        "The user interface only exposes the primary agent while hiding specialist agents from direct user interaction",
                        "Task decomposition logic exists that breaks down user requests into subtasks assigned to different agents",
                        "Inter-agent communication is logged or instrumented to track delegation overhead and latency",
                        "The system includes specialist agents with distinct capabilities or domains (e.g., FlightBookingAgent, HotelBookingAgent)",
                    ],
                },
                {
                    "id": "agent_calls_proxy_agent",
                    "name": "Agent Calls Proxy Agent",
                    "indicators": [
                        "Proxy agents are implemented as a separate tier or layer from worker agents that perform business logic",
                        "External API calls are routed through dedicated proxy agents rather than called directly by business logic agents",
                        "Proxy agents contain authentication credentials or API keys while other agents do not",
                        "The system includes specialized agents with 'Proxy' in their name or class definition that handle third-party integrations",
                        "Business logic agents make calls to proxy agents which then make the actual external API calls",
                    ],
                },
            ],
            "advanced": [],
        },
    },
    "agent_capabilities": {
        "name": "Agent-Level Capabilities",
        "chapter": 9,
        "levels": {
            "basic": [
                {
                    "id": "single_agent_baseline",
                    "name": "Single Agent Baseline",
                    "indicators": [
                        "A single agent class or component is equipped with a collection of tools accessible via function calls or API interfaces",
                        "The agent uses a reasoning framework like ReAct that combines tool selection, execution, and observation in a sequential loop",
                        "Tool execution results are fed back to the agent's reasoning component to inform subsequent decisions",
                        "The agent maintains no persistent state or memory between task executions",
                    ],
                },
                {
                    "id": "agent_specific_memory",
                    "name": "Agent-Specific Memory (Short-Term)",
                    "indicators": [
                        "The agent maintains a conversation_history or session_history data structure that persists across multiple interactions",
                        "The agent implements memory summarization or context window management to handle growing conversation state",
                        "Agent responses incorporate or reference information from previous turns in the same session",
                        "The agent's prompt construction includes historical context or memory summary alongside the current user input",
                    ],
                },
                {
                    "id": "context_aware_retrieval",
                    "name": "Context-Aware Retrieval (Simple RAG)",
                    "indicators": [
                        "The agent retrieves external documents or data before generating responses using similarity search or database queries",
                        "Retrieved context is explicitly inserted into the LLM prompt alongside the user query",
                        "The system includes a vector database or knowledge base that stores preprocessed document chunks or embeddings",
                        "The agent uses a separate retrieval component or tool that can be called with search queries",
                    ],
                },
            ],
            "intermediate": [
                {
                    "id": "advanced_rag",
                    "name": "Advanced RAG",
                    "indicators": [
                        "The RAG pipeline includes a re-ranking component that reorders retrieved documents before generation",
                        "Query transformation or reformulation occurs before the initial retrieval step",
                        "Multiple retrieval iterations are performed with refined queries based on initial results",
                        "Retrieved document chunks are filtered or scored beyond basic semantic similarity",
                        "The system implements agentic RAG with dedicated query refinement or result synthesis components",
                    ],
                },
            ],
            "advanced": [
                {
                    "id": "agentic_rag",
                    "name": "Agentic RAG & Graph-Vector Hybrid Retrieval",
                    "indicators": [
                        "The system maintains and queries a knowledge graph database alongside vector embeddings for retrieval",
                        "Retrieval queries combine both semantic vector search and graph traversal operations",
                        "The agent can dynamically build or update knowledge graph relationships based on retrieved information",
                        "Retrieved context includes both vectorized document chunks and structured graph relationship data",
                        "The system implements hybrid scoring that weights both vector similarity and graph connectivity metrics",
                    ],
                },
            ],
        },
    },
    "infrastructure": {
        "name": "System-Level Infrastructure",
        "chapter": 10,
        "levels": {
            "basic": [
                {
                    "id": "agent_auth_and_authz",
                    "name": "Agent Authentication & Authorization",
                    "indicators": [
                        "Agent service accounts are configured with specific, limited permissions rather than admin or broad access rights",
                        "Agents authenticate using service account credentials before making API calls to internal services",
                        "API calls from agents include authentication tokens or credentials in headers or request parameters",
                        "Access token expiration and refresh logic is implemented in agent code with retry mechanisms for 401 errors",
                        "Agent permissions are defined at a granular level specifying exact operations allowed rather than blanket database or API access",
                    ],
                },
            ],
            "intermediate": [
                {
                    "id": "tool_and_agent_registry",
                    "name": "Tool & Agent Registry",
                    "indicators": [
                        "A centralized registry service or data structure stores metadata about available tools and agents including their capabilities and endpoints",
                        "Agents query a registry service or lookup table to discover tools by capability name rather than using hardcoded direct calls",
                        "Tools and agents register themselves with the registry by calling a registration method that stores their metadata",
                        "The registry returns endpoint information and schemas that agents use to invoke discovered services dynamically",
                        "Agent implementations include fallback logic to handle cases where registry queries return empty results or multiple matching tools",
                    ],
                },
                {
                    "id": "event_driven_reactivity",
                    "name": "Event-Driven Reactivity",
                    "indicators": [
                        "Agents subscribe to message bus topics or event streams as continuous consumers",
                        "Agent sensing components are triggered by incoming messages or events rather than polling",
                        "A central message bus or event streaming platform (like Kafka or Pub/Sub) handles inter-agent communication",
                        "Agents publish events to named topics or channels instead of making direct synchronous calls to other agents",
                        "Event handlers or message consumers contain agent reasoning loop activation logic",
                    ],
                },
            ],
            "advanced": [],
        },
    },
    "continuous_improvement": {
        "name": "Continuous Improvement",
        "chapter": 14,
        "levels": {
            "basic": [],
            "intermediate": [],
            "advanced": [
                {
                    "id": "hybrid_workflow_architecture",
                    "name": "Hybrid Workflow Agent Architecture (Planner + Scorer)",
                    "indicators": [
                        "A planner agent generates workflow plans or task sequences that are passed to other components",
                        "A scorer agent evaluates or rates the quality of generated workflows or plans",
                        "The system contains feedback loops where scorer outputs influence planner behavior or workflow refinement",
                        "Generated workflows are iteratively improved through planner-scorer interactions rather than being executed once",
                    ],
                },
                {
                    "id": "coevolved_agent_training",
                    "name": "Coevolved Agent Training",
                    "indicators": [
                        "A planner agent and scorer agent are both present as separate components in the system",
                        "Training code includes both Supervised Fine-Tuning (SFT) and Direct Preference Optimization (DPO) methods",
                        "Agent training occurs iteratively with feedback loops between planner and scorer performance",
                        "The system implements concurrent or alternating training updates for multiple agent types",
                    ],
                },
                {
                    "id": "preference_controlled_synthetic_data",
                    "name": "Preference-Controlled Synthetic Data Generation",
                    "indicators": [
                        "Synthetic data generation functions include explicit preference or control parameters in their function signatures",
                        "Data generation processes have configured offline evaluation benchmarks or validation datasets",
                        "Human-in-the-loop validation checkpoints are implemented with manual approval gates or review workflows",
                        "Generated synthetic data undergoes periodic validation against quality metrics or drift detection",
                    ],
                },
                {
                    "id": "custom_evaluation_metrics",
                    "name": "Custom Evaluation Metrics",
                    "indicators": [
                        "Domain-specific evaluation metrics are defined as custom functions or classes separate from standard accuracy/precision metrics",
                        "Custom scoring functions include domain-specific business rules or thresholds (e.g., STEPScore, risk score calculations)",
                        "Evaluation metrics incorporate multi-step workflow quality assessment rather than single-task performance",
                        "Custom metric functions accept domain-specific parameters like loan amounts, credit scores, or compliance rules",
                    ],
                },
            ],
        },
    },
}


# ---------------------------------------------------------------------------
# Pattern ID aliases — bridge KG concept IDs to rubric pattern IDs
# Add entries as needed when KG concept IDs differ from rubric IDs.
# Format: KG_ID -> RUBRIC_ID (or vice versa)
# ---------------------------------------------------------------------------

_PATTERN_ID_ALIASES: dict[str, str] = {
    # Old MATURITY_MODEL IDs -> new rubric IDs
    "single_agent_baseline_pattern": "single_agent_baseline",
    "function_calling_pattern": "single_agent_baseline",  # merged into baseline
    "watchdog_timeout_pattern": "watchdog_timeout",
    "agent_calls_human_pattern": "agent_calls_human",
    "agent_router_pattern": "supervisor_architecture",  # subsumed
    "tool_use_pattern": "single_agent_baseline",  # part of baseline
    "adaptive_retry_pattern": "simple_retry",
    "structured_reasoning_and_self": "fractal_cot_embedding",
    "fcot_pattern": "fractal_cot_embedding",
    "instruction_fidelity_auditing_pattern": "instruction_fidelity_auditing",
    "adaptive_retry_with_prompt_mutation": "adaptive_retry_with_prompt_mutation",
    "supervisor_architecture": "supervisor_architecture",
    "multi_agent_planning": "multi_agent_planning",
    "shared_epistemic_memory": "shared_epistemic_memory",
    "event_driven_reactivity": "event_driven_reactivity",
    "tool_and_agent_registry": "tool_and_agent_registry",
    "agent_authentication_and_authorization": "agent_auth_and_authz",
    "consensus_pattern": "consensus_and_negotiation",
    "agent_negotiation": "consensus_and_negotiation",
    "blackboard_knowledge_hub": "shared_epistemic_memory",  # subsumed
    "self_correction_pattern": "fractal_cot_embedding",
    "self_improvement_flywheel": "coevolved_agent_training",
    "custom_evaluation_metrics_pattern": "custom_evaluation_metrics",
    "coevolved_agent_training_pattern": "coevolved_agent_training",
    "majority_voting_pattern": "majority_voting",
    "contract_net_marketplace": "hybrid_delegation_framework",  # subsumed
    "supervision_tree_with_guarded_capabilities": "supervisor_architecture",  # subsumed
    # Old failure template IDs -> rubric IDs
    "auto_healing_pattern": "auto_healing_agent_resuscitation",
    "auto_healing": "auto_healing_agent_resuscitation",
    "audit_trail_pattern": "basic_audit_logging",
    "agent_specific_context_and_memory": "agent_specific_memory",
    "fallback_model_invocation_pattern": "fallback_model_invocation",
    "canary_agent_testing_pattern": "canary_agent_testing",
    "trust_decay_pattern": "trust_decay_and_scoring",
    "human_calls_agent_pattern": "human_calls_agent",
    "agent_delegates_to_agent_pattern": "agent_delegates_to_agent",
    "agent_calls_proxy_agent_pattern": "agent_calls_proxy_agent",
    # KG concept IDs -> rubric IDs (concept table uses _pattern suffix)
    "causal_dependency_graph_pattern": "causal_dependency_graph",
}

# Build reverse map (rubric ID -> old ID, for first occurrence)
_PATTERN_ID_ALIASES_REVERSE: dict[str, str] = {}
for _old, _new in _PATTERN_ID_ALIASES.items():
    if _new not in _PATTERN_ID_ALIASES_REVERSE:
        _PATTERN_ID_ALIASES_REVERSE[_new] = _old

_PATTERN_ID_ALIAS_COMBINED: dict[str, str] = {
    **_PATTERN_ID_ALIASES,
    **_PATTERN_ID_ALIASES_REVERSE,
}


# All pattern IDs in the rubric
ALL_PATTERN_IDS: set[str] = {
    "adaptive_retry_with_prompt_mutation",
    "advanced_rag",
    "agent_auth_and_authz",
    "agent_calls_human",
    "agent_calls_proxy_agent",
    "agent_delegates_to_agent",
    "agent_specific_memory",
    "agentic_rag",
    "auto_healing_agent_resuscitation",
    "basic_audit_logging",
    "canary_agent_testing",
    "causal_dependency_graph",
    "coevolved_agent_training",
    "consensus_and_negotiation",
    "context_aware_retrieval",
    "custom_evaluation_metrics",
    "event_driven_reactivity",
    "fallback_model_invocation",
    "fractal_cot_embedding",
    "human_calls_agent",
    "hybrid_delegation_framework",
    "hybrid_workflow_architecture",
    "incremental_checkpointing",
    "instruction_fidelity_auditing",
    "majority_voting",
    "multi_agent_planning",
    "persistent_instruction_anchoring",
    "preference_controlled_synthetic_data",
    "rate_limited_invocation",
    "shared_epistemic_memory",
    "simple_retry",
    "single_agent_baseline",
    "supervisor_architecture",
    "tool_and_agent_registry",
    "trust_decay_and_scoring",
    "watchdog_timeout",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def normalize_pattern_id(pid: str) -> str:
    """Resolve aliases to canonical rubric ID.

    Multi-book aware: if `pid` carries a `{book_id}__` prefix (introduced in
    Phase 1c so concept IDs don't collide across books), the prefix is
    stripped before alias / canonical lookup. So both
    `arsanjani_2026__supervisor_architecture` and `supervisor_architecture`
    resolve to the same canonical rubric ID.
    """
    if pid in _PATTERN_ID_ALIASES:
        return _PATTERN_ID_ALIASES[pid]
    if "__" in pid:
        suffix = pid.split("__", 1)[1]
        if suffix in _PATTERN_ID_ALIASES:
            return _PATTERN_ID_ALIASES[suffix]
        if suffix in ALL_PATTERN_IDS:
            return suffix
    return pid


def get_pattern_indicators(pattern_id: str) -> list[str]:
    """Return indicators for a pattern, resolving aliases."""
    pid = normalize_pattern_id(pattern_id)
    for cat in RUBRIC.values():
        for level_patterns in cat["levels"].values():
            for p in level_patterns:
                if p["id"] == pid:
                    return p["indicators"]
    return []


def get_pattern_category(pattern_id: str) -> str | None:
    """Return category key for a pattern, resolving aliases."""
    pid = normalize_pattern_id(pattern_id)
    for cat_key, cat in RUBRIC.items():
        for level_patterns in cat["levels"].values():
            for p in level_patterns:
                if p["id"] == pid:
                    return cat_key
    return None


def get_pattern_level(pattern_id: str) -> str | None:
    """Return level (basic/intermediate/advanced) for a pattern."""
    pid = normalize_pattern_id(pattern_id)
    for cat in RUBRIC.values():
        for level_name, level_patterns in cat["levels"].items():
            for p in level_patterns:
                if p["id"] == pid:
                    return level_name
    return None
